---
- name: setup requirements
  become: yes
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - unzip
    - wget
    - java-{{ jdk_version }}-openjdk-devel

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Upgrade all packages
  ansible.builtin.yum:
    name: '*'
    state: latest